### ISSUE TITLE
Replace parser library

### ISSUE THREAD

**Issue by thebinarypenguin** [thebinarypenguin/raml-cop#3]
When it is ready [raml-js-parser-2](https://github.com/raml-org/raml-js-parser-2)  will be replacing [raml-js-parser](https://github.com/raml-org/raml-js-parser) and raml-cop will need to upgrade to support RAML 1.0

**Comment by amirrustam** [comment]
:+1: 
Came to the Issues section to create this exact same request.

**Comment by thebinarypenguin** [comment]
Fixed in v2.0.0 release
